version: "3.8"
services:
  webapp:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ..:/workspace
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust